import Head from "next/head";
import Image from "next/image";

const Login = () => {
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <div className="grid grid-cols-2 min-h-screen">
        <div className="py-9 px-40">
          <Image
            src={"/logo.svg"}
            width={100}
            height={80}
            alt="RumahPC Logo"
          ></Image>
          <h1 className="mt-5 text-3xl font-semibold">Login</h1>
          <form action="" className="mt-8 flex flex-col gap-3">
            <label htmlFor="" className="text-lg">
              Email or Username
            </label>
            <input
              name="emailOrUsername"
              type="text"
              required
              placeholder="yourEmail@gmail.com"
              className=" border-green-700 border-2 bg-slate-100 h-12 rounded-lg p-3 leading-normal focus:outline-none focus:bg-white"
            />
            <label htmlFor="" className="text-lg mt-2">
              Password
            </label>
            <input
              name="password"
              type="password"
              placeholder="Your password"
              className=" border-green-700 border-2 bg-slate-100 h-12 rounded-lg p-3 leading-normal focus:outline-none focus:bg-white"
            />
            <button
              type="submit"
              className="mt-5 bg-green-700 rounded-lg h-12 text-xl text-white font-semibold hover:bg-green-600"
            >
              Login
            </button>
          </form>
          <footer className="mt-40">
            <h5 className="text-neutral-500">{`Copyright \u00A9 RumahPC ${new Date().getFullYear()}`}</h5>
          </footer>
        </div>
        <div className="bg-green-700 flex justify-center items-center">
          <h1 className="font-extrabold text-white text-7xl">RUMAH + PC</h1>
        </div>
      </div>
    </>
  );
};

export default Login;
